### ISSUE TITLE
Drag'n'drop doesn't work on Android

### ISSUE THREAD

**Issue by jean** [bkkhack/hackmap#24]
Samsung Galaxy Tab A 10"
Chrome
Firefox Nightly

**Comment by waf** [comment]
This now works on my android phone (chrome and firefox). @jean I'd appreciate if you could try it out for next hacknight.

Turns out the HTML5 drag-and-drop is under-specified, so browsers have different quirks, and most mobile browsers don't support drag-and-drop at all. However, we're now using a [drag-and-drop shim](https://github.com/timruffles/mobile-drag-drop) which appears to work decently well.

**Comment by waf** [comment]
Thanks for reporting this issue! I consider this fixed.
