### ISSUE TITLE
dnd to bottom half of map doesn't work

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#65]
icon disappears. on refresh its way at the bottom of the image. 
Some weird scaling issue?

**Comment by waf** [comment]
Thanks for reporting this. Fixed in e226833e10507b037c2375f3464160115876ce7f. It had to do with scrolling the viewport; apparently the [`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) browser API returns negative position numbers in that case.
