### ISSUE TITLE
June 2018 Hack Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#66]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

If you know what you'll be hacking on, add it to the left.

The seating chart may not be up-to-date yet, but go ahead and add your plan or idea—when you arrive at the event, drag your picture to where you're sitting so others can find you. If you're not sure, you can join somebody else's hack, or ask @ches if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

**Comment by waf** [comment]
Probabilistic Programming
Learning about what this is, doing some Hello World level programs

**Comment by blisscs** [comment]
Sample Line Bot Using Elixir and Elm
I will be building a sample line bot **just for fun** as in the image below.

![linebot](https://gitlab.com/blisscs/ex-line-bot-sample/uploads/0891ce58868543ec12205aa01a8dc010/linebot.png)

**Tooling** -
1. phoenix framework. (Phoenix channel for real time support over socket)
2. elm and webpack for frontend. (elm-phoenix for real time ui update over socket)
3. Deploy on heroku

**Features**
1. Once user scan a bot barcode. that user chat windows will appears real time.
2. Once user remove a bot from a friend. that user chat window will be disappeared in real time.
3. Once user send a message to a bot. that message will be appeared on that user chat window in real time. There will be also notification on top of that particular chat window.
4. For each received message from user to bot. We can reply back by submitting a message in that particular user chat window.
5. For Each event happening. The Event Log Windows will display them in chronological order (or any other order).
6. collapsible user chat window.
7. No Sign In / No SIgn Up / No Authorization ( Just for fun only make sure that demo works )

**Limitation**
I will start with basic line dev account so. I think, the number of possible chat windows will be less than or equal to 50.

**Suggestion and Contributions are welcome**

** Estimate finish time: July 14 2018**

** Repos: **
https://gitlab.com/blisscs/ex-line-bot-sample for line bot

https://gitlab.com/blisscs/ex-line-bot-sdk for sdk 
*I am hoping to develop a sdk in elixir also as a side. so that we can reuse later*

** Development process / issues / progress / contributions can be track and contributed on the repos above**

**Comment by danfowler** [comment]
Setting up Emacs as a Python IDE

**Comment by mrik23** [comment]
Wargames overthewire.org
http://overthewire.org/wargames/natas/

**Comment by ianmere** [comment]
Crypto Bot
Monitoring, and looking to improve with machine learning

**Comment by elcolie** [comment]
Getting start with Redux
Imitate the tutorial, but I do by my IDE not online IDE like in the example.

**Comment by vehas** [comment]
clojure server w/ mongo db

**Comment by fredpolito** [comment]
testing webapps with burpsuite
web application testing with BurpSuite (security)

**Comment by fredpolito** [comment]
testing webapps with burpsuite
web application testing with BurpSuite (security)

**Comment by Objectoop** [comment]
Blockchain
I am actually beginner in blockchain.  
Welcome to share :)

1. P2P Network programming.
2. Proof of work, Proof of stake

**Comment by siraben** [comment]
Relational Programming in Scheme

**Comment by mohamedhayibor** [comment]
Build a meme marketplace with Ethereum
* Already wrote the smart contracts
* The main work is in wiring the front end to the deployed smart contracts

If you are pro-efficient with front-end stuff, let's hack away together.

The goal is that by the end, we will have a full working front end (github page) interacting with the deployed smart contract. So 80% to 90% finished and usable.

repo: https://github.com/mohamedhayibor/ethervineAlpha

**Comment by yrashk** [comment]
Decentralized collaboration
What's decentralized collaboration and showcasing https://sit.fyi

**Comment by caspar-goeke** [comment]
Multi-Layered Online Strategy Game
I started with this project ~5 years ago and together with a friend of mine, we got quite a few nice features working, but not enough for a Beta Version / simple demo.

So my current task is: Improving the procedureal map/ terrain generation mechanism to procude a nicer map/ landscape.

**Comment by drawnwren** [comment]
Haskell Codewars
Working through simple Haskell coding problems. Great if you are either a beginning programmer who wants to think about basic algorithms or an advanced programmer who wants to learn Haskell.

**Comment by teguesimo** [comment]
R, Python ,data science
