### ISSUE TITLE
BKK/Hack Oct 2018

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#73]
Welcome to BKK/hack!  (Best viewed on  https://bkkhack.github.io/hackmap)

A hack is what you'd really like to work on if you can. 

1. Add your idea on the left
2. Drag your face onto the map. Just pick anywhere or next to someone doing something similar.

Do this as soon as you RSVP and update it often.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

**Comment by elcolie** [comment]
Solve XOR by using PyTorch
Solve the XOR gate by PyTorch
https://stackoverflow.com/questions/52738146/xor-neural-network-does-not-learn

**Comment by crishoj** [comment]
Make KivyPie distro run on RPi 3 B+
[KivyPie](http://kivypie.mitako.eu/) is PipaOS (Raspbian derivative) bundled with the [Kivy](https://kivy.org/) framework. The current version works on Raspberry Pi’s up to 3 B, but not 3 B+. I want to fork KivyPie and upgrade the underlying Raspbian realease, in order to make it run on the 3 B+ hardware.

**Comment by thanonk** [comment]
React-native firebase app with notifictn

**Comment by thaxy** [comment]
Website for a Research Group at KU (BKK)
I am working for several days on a website for a friend at Kasetsart University. I use this project to learn *modern* technologies that are new to me, like Webpack and React (I recently finished the book 'the road to learn react').

My final stack would be:
 * Docker with Docker Compose
 * Caddy (webserver)
 * postgres DB
 * Django with wagtail CMS 
 * Bulma CSS Framework
 * webpack

My project structure is similar to those of cookiecutter-django (book 'two scopes of django'). There is still a lot to do and I haven't integrated everything mentioned above. Since I am coming more from a backend site I am currently struggling to design the frontend ;).

This is my first time here and I am more interested in talking to other people and hearing different opinions than doing heavy lifting stuff this evening.

**Comment by chinnathan** [comment]
Using Pandas for Analyzing Data
Using Pandas for Analyzing Data - Visualization

**Comment by SuperCipher** [comment]
Rust and AI
learn to use rust to doing some fundamental AI

**Comment by djay** [comment]
Write my Talk for PloneConf2018

**Comment by doublekang** [comment]
RPA
utililize gow to use RPA ,web scrape , human interface to reduce people burden

**Comment by jean** [comment]
Prepare my talk for PloneConf 2018
I'm going to be presenting and contrasting the Orchard Core CMS to the Plone CMS, specifically with regards to content type design, page layouts, and approaches to theming.

**Comment by hirokihokari** [comment]
django app

**Comment by toastal** [comment]
FP discussions
Wanna talk (or debate) about the merits and concepts of functional programming?

Currently I'm doing Elm. In the past I've worked with ClojureScript and PureScript, and have hobbied Haskell a little bit.

I'll be modeling some data in meantime.

**Comment by saiqulhaq** [comment]
Create Instagram scraper
Using Ruby

**Comment by dwsmith1983** [comment]
maybe python

**Comment by shubham0794x** [comment]
Full Stack Javascript : React
Implementing React with nodejs

**Comment by ditsara** [comment]
contributing to Universal CTags

**Comment by whitemalt** [comment]
maybe hecktober fest

**Comment by jaznoAlpha** [comment]
Angular - Ionic Mostly Front-End

**Comment by gaurav-pantelwar** [comment]
No Hack yet
Worked on Angular, React, iOS, Android,  Kivy. 
Want to learn more about ML and AI

**Comment by gandharv-pantelwar** [comment]
MEAN Stack
Worked at the Backend on Node js, Golang. Databases-Mongo and Postgresql

Wants to learns about AI and ML.
