### ISSUE TITLE
January 2020 Project Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#81]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

### How This Works

A hack is a project you'd like to do (or learn) at hack night.

1. Add your idea on the left. In advance of the Meetup date is great.
1. Drag your picture onto the seating map when you arrive. Wherever you wish, or near someone doing something similar.

If you're not sure, you can join someone else's hack, or ask the organizers if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

Have fun!

**Comment by Scheffti** [comment]
Lao Microfinance Villagebanking system
Hi, I am building a System for village banks in Laos for about 150,000 clients. The stack is C#/ Visual studio / PostgreSQL / win server 2019. Super interested to share, learn and get feed forward. Specially on MVVM .NET two-languages-in-the-application (Lao/English). decentral deployment / on-/offline synchronization, etc. I am also interested in cooperating and teaming up with teams to tackle tasks. Cheers, Tim tim.scheffmann@gmail.com

**Comment by udomsak** [comment]
Learn [Go / FrontEnd ] - Shop Assistant
Shop Assistant.

=== Problem ===

Last few days ago, i got question / pain point about Shipping agency. when their client found some product next they must pate URL of the item in msg. box So shipping will collect later.   

=== Solution ===
Instead of crawler or complex, mind idea just use concept of analytic platform with JS client that embed as Browser extension then make overlay or form submission then send back to server that shipping can get report about orders easier. 

=== Stack === 

JS analytics platform  + customize. 
Golang as gateway for message ( may be gRPC stub ) 
Nasts as message queue. 


===  Question ===
 
It's possible to involve to business case and useful service in feature ? 
Other from technical feedback ?

**Comment by udomsak** [comment]
Learn [Go / FrontEnd ] - Shop Assistant
Shop Assistant.

=== Problem ===

Last few days ago, i got question / pain point about Shipping agency. when their client found some product next they must pate URL of the item in msg. box So shipping will collect later.   

=== Solution ===
Instead of crawler or complex, mind idea just use concept of analytic platform with JS client that embed as Browser extension then make overlay or form submission then send back to server that shipping can get report about orders easier. 

=== Stack === 

JS analytics platform  + customize. 
Golang as gateway for message ( may be gRPC stub ) 
Nasts as message queue. 


===  Question ===
 
It's possible to involve to business case and useful service in feature ? 
Other from technical feedback ?

**Comment by jrreyes29** [comment]
Computer Vision Tool
I'm starting in the computer vision world and I is a super challenge topic about how use the browser for run differents algorithm.

Proposal:
Start to build a small proof of concept for use superpixel algorithm and do it interactive.

**Comment by jraut** [comment]
OCR / Table parsing
Check out the current state of Camelot library to see what it can do.

**Comment by bmason** [comment]
enhance Torrent manager
https://myally.co/content/torrent-manager-tm

**Comment by cronty** [comment]
Data pipeline
Replication all data from a Amazon MWS seller account to a bigQuery data warehouse and keep the data synced.
